#!/bin/bash

# Update the game
steamcmd +force_install_dir /home/ubuntu/pzserver +login anonymous +app_update 380870 +quit

cd /home/ubuntu/pzserver

./start-server.sh -Xms$PZ_JAVA_XMS -Xmx$PZ_JAVA_XMX -- \
    -adminusername $PZ_ADMIN_USERNAME \
    -adminpassword $PZ_ADMIN_PASSWORD \
    -servername $PZ_SERVER_NAME \
    -steamvac $PZ_STEAM_VAC